version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data

  redis:
    image: redis:latest
    container_name: redis-base
    environment:
      - REDIS_PASSWORD=default
      - REDIS_USER=default
      - REDIS_USER_PASSWORD=default
    ports:
      - "6379:6379"
    volumes:
      - ./redisbase:/data
    networks:
      - redis-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight:/data
    networks:
      - redis-network

  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enrollment.enabled: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - logging-network

  kibana:
    image: kibana:8.15.5
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge

  redis-network:
    driver: bridge